# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
    vb.gui = false
  end

  def configure_box (machine)
    machine.vm.box = "centos/7"
    machine.vm.box_check_update = false
    machine.ssh.insert_key = false
    machine.vm.provision "shell", inline: <<-SHELL
      echo "hello"
    SHELL
  end
  
  config.vm.define "gitlab" do |es|
    configure_box(es)
    es.vm.network "private_network", ip: "192.168.99.11"
  end

end
